# Command-line essentials
brew "git"
brew "go"
brew "bun"
brew "pyenv"
brew "nvm"
brew "starship"
brew "tmux"
brew "fzf"
brew "zoxide"
brew "ripgrep"
brew "fd"
brew "bat"
brew "eza"
brew "jq"
brew "yq"
brew "direnv"
brew "micro"
brew "lazygit"
brew "lazydocker"
brew "kubectl"
brew "k9s"

# Desktop applications
cask "ghostty"
cask "visual-studio-code"
cask "tableplus"
cask "font-jetbrains-mono-nerd-font"

# VS Code language support and formatters
vscode "golang.go"
vscode "ms-python.python"
vscode "ms-python.vscode-pylance"
vscode "charliermarsh.ruff"
vscode "zhuangtongfa.material-theme"
